### ISSUE TITLE
Install Software option should provide an indication of what will be installed

### ISSUE THREAD

**Issue by python33r** [codio/install_software#9]
It isn't always obvious what will be installed by one of the options available from _Tools_ > _Install Software_. For example, 'Python 3 tools set' doesn't indicate which items will be installed. You only find out by inspecting the not-very-user-friendly output generated by the install process!

It would be good to see a list of items appearing somewhere. Perhaps the package title could become a link that expands when clicked to show the individual items (name and version) that make up the package?

Obviously, this isn't critical given that full control over installation is always possible via the command line, but it would be nice to have...

**Comment by fmay** [comment]
This is a good suggestion. We will discuss this internally and look what we can do. It won't be in the very short term as we have quite a lot on, unless it is a trivial add, which it could be.

**Comment by MaximKraev** [comment]
it is not so easy as user can install some components manually or from different sources
